#!/bin/sh
set -e

# Start Systemd or Upstart
if [ -e "/bin/systemctl" ]; then
		if [ -e "/etc/systemd/system/multi-user.target.wants/radeon-profile-daemon.service" ]; then
			echo "Radeon profile daemon is enabled"
			echo "Continuing to stop service"
			systemctl stop radeon-profile-daemon.service
		else
			echo "Radeon profile daemon is not enabled"
			echo "Nothing to stop"
		fi
else
		echo "Upstart is installed"
		echo "Stopping Upstart"
		service radeon-profile-daemon stop
fi

exit 0
